### ISSUE TITLE
How to Retrieve correct data with multiple consecutive calls ?

### ISSUE THREAD

**Issue by zirid** [cppengineer/asio-wrapper#1]
![Asio](https://github.com/jpret/asio-wrapper/assets/31682698/6144335f-82dc-4ff8-8a17-8f4e8c960067)

Is there any way to prevent data concatenation after multiple writes?  

Update :

![no_Delay](https://github.com/jpret/asio-wrapper/assets/31682698/e31246e1-5813-4f6a-83d9-efcfdef5ea5a)

I also noticed that the wrapper write function is implemented in a such way that the 2nd message is lost if the boost::asio write function is busy writing.

```
void Connection::Write(const std::string &data) {
  // Add the data to the queue
  write_queue_.emplace(data.begin(), data.end());
  // Start the write process only if we are not already busy writing
  if (!write_busy_) {
    write_busy_ = true;
    DoWrite();
  }
  else {
     
  }
}
```

**Comment by sehe** [comment]
To the second complaint: how do you reach that conclusion? The code you cite doesn't cause lost messages, because the message is added to the queue. I'm not sure that asio_wrapper correctly uses strands to protect against data races though. See how I treated it in my answer [here](https://stackoverflow.com/a/77327932/85371)

**Comment by jpret** [comment]
@zirid, thank you for raising your question and @sehe thank you for answering the question in more details on StackOverflow.

As @sehe mentioned on SO. Transferring the message over the socket and reading them as separate messages are 2 different things. It really depends on your use case. 

I propose you add all received data to a container that you can parse or analyze by checking for delimiters in your message. What we've done for simple protocols before in our team is simply using the ASCII codes for that e.g.

\<SOH\>heading info here\<STX\>Text body here\<ETX\>\<EOT\>

Where the hex codes for the above as stated at https://www.ascii-code.com/ are:
\<SOH\> = 0x01
\<STX\> = 0x02
\<ETX\> = 0x03
\<EOT\> = 0x04

The second issue has already been answered by @sehe.

Thanks for trying out the wrapper and if you have any suggestions for improvement please share them or feel free to contribute.

Happy Coding!

Ps: if this solves your problem, please indicate so, then I can close this issue.
